<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="UnitTestProgram" Id="{6ee97de3-1527-4e60-9cef-4d70f0e42f35}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM UnitTestProgram
VAR
	MotorControl_Test : FB_MotorControl_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="UnitTestProgram">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>